services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms
      POSTGRES_DB: cms
    ports:
      - "5432:5432"
    volumes:
      - cms_db_data:/var/lib/postgresql/data

volumes:
  cms_db_data:
